version: '3.9'

services:

  node-pgdb:
    image: postgres:16.2-bullseye
    restart: always
    shm_size: 256mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: e_shop_db
      POSTGRES_PASSWORD: qazwsx

    ports: 
      - "10000:5432"

    volumes:
      - "./data:/var/lib/postgresql/data"

